### ISSUE TITLE
Pi Hole Dash not showing first 1/3 graphs

### ISSUE THREAD

**Issue by himuura** [Brandawg93/Pi-Hole-Monitoring#7] opened 2019-12-23 17:26 UTC
Hey there! I'm not sure what's happening but the thing is i have Pi hole on a container (docker) and working fine. I'm running your stack and also working fine (i pointed the /etc/pihole directory to the container directory of my pihole). On grafana, accessing the pi hole dash, my first row of graphs and last two don't display any data (the first one displays N/A message). Any clues on how to solve it?

**Comment by Brandawg93** [comment] 2019-12-23 18:04
Duplicate of #5

**Closed as completed by Brandawg93** 2019-12-23 18:04 UTC
